[project]
name = "ebooklib-autoupdate"
version = "0.18.1"
description = "A self-updating fork of the Ebooklib library"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "lxml>=4.9.0",
    "six>=1.0.0",
]
