name: Auto-Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  VERSION_FILE: VERSION.txt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/aerkalov/ebooklib || echo "Upstream already added"
          git fetch upstream

      - name: Read fork version
        id: fork_state
        run: |
          CURRENT_VERSION=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' "${{ env.VERSION_FILE }}")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Add GitHub Action Bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if upstream has changes
        id: upstream_changes
        run: |
          VERSION_TIMESTAMP=$(git log -1 --format=%at -- ${{ env.VERSION_FILE }})
          if [[ $(git log upstream/master -1 --format=%at) -gt $VERSION_TIMESTAMP ]]; then
            echo "updated_version=true" >> $GITHUB_OUTPUT
          else
            echo "updated_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge upstream changes
        if: steps.upstream_changes.outputs.updated_version == 'true'
        run: |
          {
            echo "${{ env.VERSION_FILE }} merge=theirs"
          } > .gitattributes
          git merge upstream/master --no-edit

      - name: Update files
        if: steps.upstream_changes.outputs.updated_version == 'true'
        uses: ./.github/workflows/update-files.yml
        with:
          updated_version: ${{ steps.upstream_changes.outputs.updated_version }}

      - name: Sync new branches
        run: |
          git fetch --all
          for BRANCH in $(git branch -r | grep "upstream/" | grep -v "HEAD" | sed 's/upstream\///'); do
            if [ "$BRANCH" == "master" ]; then
              continue
            fi
            if ! git show-ref --verify --quiet "refs/heads/$BRANCH"; then
              git branch "$BRANCH" "upstream/$BRANCH"
            else
              git checkout "$BRANCH"
              git merge -s recursive -X theirs "upstream/$BRANCH" --no-edit
            fi
            git push -f origin "$BRANCH"
          done