name: Process Local Changes

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  process:
    uses: ./.github/workflows/update-files.yml
    with:
      updated_version: true